// flow-typed signature: 2e1b0041672e485146f4879981fb861c
// flow-typed version: <<STUB>>/@testing-library/jest-dom_v^4.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/jest-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/jest-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/jest-dom/dist/__tests__/helpers/document' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/helpers/test-utils' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-be-disabled' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-be-empty' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-be-in-the-document' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-be-in-the-dom' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-be-invalid' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-be-required' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-be-visible' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-contain-element' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-contain-html' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-have-attribute' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-have-class' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-have-focus' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-have-form-values' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-have-style' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-have-text-content' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/to-have-value' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/__tests__/utils' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/extend-expect' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/index' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-be-disabled' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-be-empty' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-be-in-the-document' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-be-in-the-dom' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-be-invalid' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-be-required' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-be-visible' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-contain-element' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-contain-html' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-have-attribute' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-have-class' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-have-focus' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-have-form-values' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-have-style' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-have-text-content' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/to-have-value' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/dist/utils' {
  declare module.exports: any;
}

declare module '@testing-library/jest-dom/extend-expect' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/jest-dom/dist/__tests__/helpers/document.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/helpers/document'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/helpers/test-utils.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/helpers/test-utils'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-be-disabled.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-be-disabled'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-be-empty.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-be-empty'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-be-in-the-document.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-be-in-the-document'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-be-in-the-dom.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-be-in-the-dom'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-be-invalid.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-be-invalid'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-be-required.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-be-required'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-be-visible.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-be-visible'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-contain-element.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-contain-element'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-contain-html.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-contain-html'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-have-attribute.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-have-attribute'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-have-class.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-have-class'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-have-focus.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-have-focus'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-have-form-values.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-have-form-values'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-have-style.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-have-style'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-have-text-content.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-have-text-content'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/to-have-value.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/to-have-value'>;
}
declare module '@testing-library/jest-dom/dist/__tests__/utils.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/__tests__/utils'>;
}
declare module '@testing-library/jest-dom/dist/extend-expect.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/extend-expect'>;
}
declare module '@testing-library/jest-dom/dist/index.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/index'>;
}
declare module '@testing-library/jest-dom/dist/to-be-disabled.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-be-disabled'>;
}
declare module '@testing-library/jest-dom/dist/to-be-empty.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-be-empty'>;
}
declare module '@testing-library/jest-dom/dist/to-be-in-the-document.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-be-in-the-document'>;
}
declare module '@testing-library/jest-dom/dist/to-be-in-the-dom.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-be-in-the-dom'>;
}
declare module '@testing-library/jest-dom/dist/to-be-invalid.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-be-invalid'>;
}
declare module '@testing-library/jest-dom/dist/to-be-required.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-be-required'>;
}
declare module '@testing-library/jest-dom/dist/to-be-visible.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-be-visible'>;
}
declare module '@testing-library/jest-dom/dist/to-contain-element.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-contain-element'>;
}
declare module '@testing-library/jest-dom/dist/to-contain-html.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-contain-html'>;
}
declare module '@testing-library/jest-dom/dist/to-have-attribute.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-have-attribute'>;
}
declare module '@testing-library/jest-dom/dist/to-have-class.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-have-class'>;
}
declare module '@testing-library/jest-dom/dist/to-have-focus.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-have-focus'>;
}
declare module '@testing-library/jest-dom/dist/to-have-form-values.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-have-form-values'>;
}
declare module '@testing-library/jest-dom/dist/to-have-style.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-have-style'>;
}
declare module '@testing-library/jest-dom/dist/to-have-text-content.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-have-text-content'>;
}
declare module '@testing-library/jest-dom/dist/to-have-value.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/to-have-value'>;
}
declare module '@testing-library/jest-dom/dist/utils.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/dist/utils'>;
}
declare module '@testing-library/jest-dom/extend-expect.js' {
  declare module.exports: $Exports<'@testing-library/jest-dom/extend-expect'>;
}
